# Generated by Django 4.2 on 2026-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compare_images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparisonresult",
            name="ai_description",
            field=models.TextField(blank=True),
        ),
    ]
